version: '3.4'

services:
  blazor.server:
    container_name: "front"
    image: ${DOCKER_REGISTRY-}blazorserver
    build:
      context: .
      dockerfile: Blazor/Server/Dockerfile
  blazor.grpc:
    container_name: "back"
    image: ${DOCKER_REGISTRY-}blazorgrpc    
    build:
      context: .
      dockerfile: Blazor/Grpc/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04"    
    container_name: "db"
  

